# Browser Config
base.url=https://freelance-learn-automation.vercel.app
browser.type=chromium
headless=false
timeout=10000

# Test Credentials
user.email=admin@email.com
user.password=admin@123

user.unregemail=singh.j@gmail.com
